---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: kubernetes-calico
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: kubernetes-calico-global
    actions:
      - method: merge
        path: .
  substitutions:
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.bgp.ipv4.public_service_cidr
      dest:
        path: .values.networking.bgp.ipv4.additional_cidrs[0]

    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.bgp.ipv4.peers[0]
      dest:
        path: .values.networking.bgp.ipv4.peers[0].spec.peerIP
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.bgp.ipv4.peers[1]
      dest:
        path: .values.networking.bgp.ipv4.peers[1].spec.peerIP

  storagePolicy: cleartext
data:
  values:
    networking:
      settings:
        mesh: "off"
        ippool:
          ipip:
            enabled: "false"
      bgp:
        asnumber: 65205
        ipv4:
          peers:
            - apiVersion: projectcalico.org/v3
              kind: BGPPeer
              metadata:
                name: peer-0
              spec:
                asNumber: 65201
            - apiVersion: projectcalico.org/v3
              kind: BGPPeer
              metadata:
                name: peer-1
              spec:
                asNumber: 65201

...


