---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-controller
  labels:
    name: openstack-ingress-controller-global
    component: ingress
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.ingress
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.ingress
      dest:
        path: .values.images.tags
data:
  chart_name: openstack-ingress-controller
  release: openstack-ingress-controller
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: airship-openstack-ingress-controller
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-openstack-ingress-controller
  values: 
    conf: 
      ingress: 
        proxy-body-size: 10000m 
    labels: 
      server: 
        node_selector_key: ucp-control-plane 
        node_selector_value: enabled 
      error_server: 
        node_selector_key: ucp-control-plane 
        node_selector_value: enabled 
    pod: 
      replicas: 
        ingress: 2
        error_page: 2 
  #  network: 
  #    ingress: 
  #      annotations: 
  #        nginx.ingress.kubernetes.io/proxy-body-size: 10000m 
  #        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  dependencies:
    - osh-helm-toolkit
