---
# NOTE: This file is ignored by Airskiff and is copied from the seaworthy site.

schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: elasticsearch
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      hosttype: elasticsearch-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data: {}
...
